WEEK 10/13.02.2024/AllUpThemeplate/Models/ErrorViewModel.cs
namespace AllUpThemeplate.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

WEEK 10/13.02.2024/AllUpThemeplate/Models/Feature.cs
namespace AllUpThemeplate.Models;

public class Feature
{
    public int Id { get; set; }
    public string ImageUrl { get; set; } = string.Empty;
    public string Title { get; set; }  = string.Empty;
    public string Description { get; set; }  = string.Empty;
}

WEEK 10/13.02.2024/AllUpThemeplate/Areas/Admin/Controllers/FeaturesController.cs
using AllUpThemeplate.Data;
using AllUpThemeplate.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AllUpThemeplate.Areas.Admin.Controllers;

[Area("Admin")]
public class FeaturesController : Controller
{
    private readonly ApplicationDbContext _context;

    public FeaturesController(ApplicationDbContext context)
    {
        _context = context;
    }


    public async Task<IActionResult> Index()
    {
        return View(await _context.Features.ToListAsync());
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("ImageUrl,Title,Description")] Feature feature)
    {
        if (ModelState.IsValid)
        {
            _context.Add(feature);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        return View(feature);
    }


    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var feature = await _context.Features.FindAsync(id);
        if (feature == null)
        {
            return NotFound();
        }

        return View(feature);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,ImageUrl,Title,Description")] Feature feature)
    {
        if (id != feature.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            _context.Update(feature);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        return View(feature);
    }

    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var feature = await _context.Features
            .FirstOrDefaultAsync(m => m.Id == id);
        if (feature == null)
        {
            return NotFound();
        }

        return View(feature);
    }

    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var feature = await _context.Features.FindAsync(id);

        if (feature == null)
            return NotFound();
        
        _context.Features.Remove(feature);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }
}

WEEK 10/13.02.2024/AllUpThemeplate/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace AllUpThemeplate.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        // GET: HomeController
        public ActionResult Index()
        {
            return View();
        }

    }
}

WEEK 10/13.02.2024/AllUpThemeplate/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AllUpThemeplate.Models;

namespace AllUpThemeplate.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

WEEK 10/13.02.2024/AllUpThemeplate/Areas/Admin/Views/Features/Create.cshtml
@model AllUpThemeplate.Models.Feature

@{
    ViewData["Title"] = "Create";
}

<main>
    <div class="container-fluid px-4">
        <h1 class="mt-4">Feature</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active">Index</li>
        </ol>
        <div class="row">
            <div class="col-xl-6">
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-plus me-1"></i>
                        Create feature
                    </div>
                    <div class="card-body">
                        <form asp-action="Create">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                            <div class="form-group mb-3">
                                <label asp-for="Title" class="control-label"></label>
                                <input asp-for="Title" class="form-control"/>
                                <span asp-validation-for="Title" class="text-danger"></span>
                            </div>

                            <div class="form-group mb-3">
                                <label asp-for="Description" class="control-label"></label>
                                <input asp-for="Description" class="form-control"/>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>

                            <div class="form-group mb-3">
                                <label asp-for="ImageUrl" class="control-label"></label>
                                <input asp-for="ImageUrl" class="form-control"/>
                                <span asp-validation-for="ImageUrl" class="text-danger"></span>
                            </div>


                            <div class="form-group">

                                <button class="btn btn-success btn-sm float-end" type="submit">
                                    <i class="fas fa-plus"></i> Save
                                </button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>

        </div>

        <div>
            <a asp-area="admin" asp-controller="Features" asp-action="index">Back to List</a>
        </div>
    </div>
</main>

WEEK 10/13.02.2024/AllUpThemeplate/Areas/Admin/Views/Features/Delete.cshtml
@model Feature

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<main>
    <div class="container-fluid px-4 p-3">
        <h2>Delete</h2>

        <h3>Are you sure you want to delete this?</h3>

        <div class="row ">

            <hr/>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Title)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Title)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ImageUrl)
            </dt>
            <dd class="col-sm-10">
                <img style="width: 150px;height: 150px" src="@Model.ImageUrl" alt="Image"/>
            </dd>

            <form asp-action="Delete" class="mt-5">
                <input type="hidden" asp-for="Id"/>
                <input type="submit" value="Delete" class="btn btn-danger "/>
                @* <a asp-action="Index">Back to List</a> *@
            </form>
        </div>

    </div>
    <div>
        <a asp-area="admin" asp-controller="Features" asp-action="index">Back to List</a>
    </div>
</main>

WEEK 10/13.02.2024/AllUpThemeplate/Areas/Admin/Views/Features/Edit.cshtml
@model Feature

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
<main>
    <div class="container-fluid px-4">
        <h1 class="mt-4">Feature</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active">Index</li>
        </ol>
        <div class="row">

            <div class="col-xl-6">
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-plus me-1"></i>
                        Edit feature
                    </div>
                    <div class="card-body">
                        <form asp-action="Edit">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group mb-3">
                                <label asp-for="Title" class="control-label"></label>
                                <input asp-for="Title" class="form-control" />
                                <span asp-validation-for="Title" class="text-danger"></span>
                            </div>
                            
                            <div class="form-group mb-3">
                                <label asp-for="Description" class="control-label"></label>
                                <input asp-for="Description" class="form-control" />
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                            
                            <div class="form-group mb-3">
                                <label asp-for="ImageUrl" class="control-label"></label>
                                <input asp-for="ImageUrl" class="form-control" />
                                <span asp-validation-for="ImageUrl" class="text-danger"></span>
                            </div>
                            

                            <div class="form-group">

                                <button class="btn btn-success btn-sm float-end" type="submit">
                                    <i class="fas fa-plus"></i> Save
                                </button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>

        </div>

        <div>
            <a asp-area="admin" asp-controller="Features" asp-action="index">Back to List</a>
        </div>
    </div>
</main>

WEEK 10/13.02.2024/AllUpThemeplate/Areas/Admin/Views/Features/Index.cshtml
@model IEnumerable<AllUpThemeplate.Models.Feature>

@{
    ViewData["Title"] = "Index";
}


<main>
    <div class="container-fluid px-4">
        <h1 class="mt-4">Feature</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active ">
                <a asp-area="admin" asp-action="create" class="btn btn-sm btn-outline-dark ">Create New</a>
            </li>
        </ol>
        <table class="table" id="datatablesSimple">
            <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ImageUrl)
                </th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        <img style="height: 150px; width: 150px" src="@item.ImageUrl" alt="Image" />
                        
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary mr-2">Edit</a> 
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</main>